<script lang="ts">
  import { ArrowRight, Check, Github } from "lucide-svelte";
  import luxHappy from "@phoxia/lux/assets/lux/lux-happy.svg?url";
  import luxConfused from "@phoxia/lux/assets/lux/lux-confused.svg?url";
  import luxProtective from "@phoxia/lux/assets/lux/lux-protective.svg?url";
  import luxExplaining from "@phoxia/lux/assets/lux/lux-explaining.svg?url";
  import Header from "$lib/components/Header.svelte"; import Footer from "$lib/components/Footer.svelte"; import CopyCommand from "$lib/components/CopyCommand.svelte"; import EvidenceThread from "$lib/components/EvidenceThread.svelte";
  import { landingContent } from "$lib/content/landing.ts"; import { translations } from "$lib/i18n/content.ts"; import { landingTranslations } from "$lib/i18n/landing.ts"; import { localeState } from "$lib/i18n/store.svelte.ts";
  let common = $derived(translations[localeState.current]); let copy = $derived(landingTranslations[localeState.current]);
</script>
<svelte:head><title>Phoxia • Kit</title><meta name="description" content={common.subtitle} /></svelte:head>
<Header />
<main id="content">
  <section data-section="hero" class="hero section"><div class="hero-copy"><p class="eyebrow">{copy.eyebrow}</p><h1>{common.title}</h1><p class="lead">{common.subtitle}</p><p>{copy.intro}</p><div class="hero-actions"><a class="button" href="#install">{copy.start}<ArrowRight size={17} /></a><a class="button secondary" href="/docs">{copy.read}</a></div></div><div class="hero-demo"><img src={luxHappy} alt={common.luxLabel} /><div class="terminal"><div class="terminal-bar"><i></i><i></i><i></i><span>terminal</span></div><div class="terminal-body"><div class="terminal-line command"><span>$</span> {landingContent.installCommand}</div><div class="terminal-line brand-line"><b>◆ Phoxia DevKit</b></div><div class="terminal-line">{copy.terminalQuestion}</div><div class="terminal-line">◆ {copy.terminalReading}</div><div class="terminal-line success"><span>✓</span> Claude Code</div><div class="terminal-line success"><span>✓</span> Codex</div><div class="terminal-line ready"><span>✓</span> {copy.terminalReadyLocal}<i aria-hidden="true"></i></div></div></div></div></section>
  <section data-section="evidence" class="wrapper"><EvidenceThread eyebrow={copy.evidence} title={copy.evidenceTitle} nodes={copy.evidenceNodes} ariaLabel={copy.evidenceAria} /></section>
  <section data-section="problem" class="section"><div class="section-heading"><img class="lux-side" src={luxConfused} alt="" /><p class="eyebrow">{copy.problem}</p><h2>{copy.problemTitle}</h2></div><div class="cards grid-4">{#each copy.problemCards as card}<article><h3>{card[0]}</h3><p>{card[1]}</p></article>{/each}</div></section>
  <section data-section="help" id="product" class="section source"><div><p class="eyebrow">{copy.help}</p><h2>{copy.helpTitle}</h2><p>{copy.helpText}</p><ul>{#each landingContent.paths.slice(0,3) as path}<li><Check size={16}/><code>{path}</code></li>{/each}</ul></div><img src={luxProtective} alt="" /></section>
  <section data-section="workflow" id="how" class="section"><div class="row"><div><p class="eyebrow">{copy.workflow}</p><h2>{copy.workflowTitle}</h2></div><img src={luxExplaining} alt="" /></div><ol class="steps">{#each landingContent.workflow as step, i}<li><span>{i+1}</span><h3>{localeState.current === "pt-BR" ? ["Inicializar","Descrever projeto","Trabalhar com IA","Verificar","Manter sincronizado"][i] : step}</h3></li>{/each}</ol></section>
  <section data-section="profiles" class="section"><p class="eyebrow">{copy.profiles}</p><h2>{copy.profilesTitle}</h2><div class="cards grid-3">{#each copy.profileCards as card}<article><h3>{card[0]}</h3><p>{card[1]}</p><code>{card[2]}</code></article>{/each}</div></section>
  <section data-section="generated-files" class="section"><p class="eyebrow">{copy.files}</p><h2>{copy.filesTitle}</h2><div class="cards grid-3 generated">{#each landingContent.paths.slice(0,3) as path}<article><h3><code>{path}</code></h3><pre>{path === ".phoxia/project.yaml" ? "name: payments-api\ntargets: [claude, codex]" : "# Managed by Phoxia DevKit\nReview before applying."}</pre></article>{/each}</div><div class="verify"><h3>{copy.verify}</h3><p>{copy.verifyText}</p><code>phxdk doctor · phxdk status</code></div></section>
  <section data-section="transparency" class="section"><p class="eyebrow">{copy.transparency}</p><h2>{copy.transparencyTitle}</h2><div class="impact">{#each copy.impact as item}<article><b>{item[0]}</b><code>{item[1]}</code></article>{/each}</div></section>
  <section data-section="setup-modes" class="section"><p class="eyebrow">{copy.modes}</p><h2>{copy.modesTitle}</h2><div class="cards grid-3">{#each copy.modeCards as card}<article><h3>{card[0]}</h3><p>{card[1]}</p></article>{/each}</div></section>
  <section data-section="trust" class="section"><p class="eyebrow">{copy.trust}</p><h2>{copy.trustTitle}</h2><div class="cards grid-3">{#each copy.trustCards as card}<article><h3>{card[0]}</h3><p>{card[1]}</p></article>{/each}</div></section>
  <section data-section="newcomer" class="section"><p class="eyebrow">{copy.newcomer}</p><h2>{copy.newcomerTitle}</h2><ol class="newcomer">{#each copy.newcomerSteps as step, i}<li><span>{i+1}</span>{step}</li>{/each}</ol></section>
  <section data-section="install" id="install" class="section install"><img src={luxHappy} alt=""/><p class="eyebrow">{copy.install}</p><h2>{copy.installTitle}</h2><p>{copy.installText}</p><CopyCommand command={landingContent.installCommand} label={copy.copyCommand} copy={copy.copy} copiedLabel={copy.copied} failedLabel={copy.copyFailed}/><div class="hero-actions"><a class="button" href="/quick-start">{common.getStarted}<ArrowRight size={17}/></a><a class="button secondary" href={landingContent.urls.repository}><Github size={17}/>{copy.github}</a></div></section>
</main>
<Footer />
