<script lang="ts">
  import { ArrowRight, BadgeAlert, BrainCircuit, Braces, FileWarning, Github, HardDrive, LockKeyhole, UserCheck } from "lucide-svelte";
  import luxHappy from "@phoxia/lux/assets/lux/lux-happy.svg?url";
  import luxConfused from "@phoxia/lux/assets/lux/lux-confused.svg?url";
  import luxExplaining from "@phoxia/lux/assets/lux/lux-explaining.svg?url";
  import Header from "$lib/components/Header.svelte"; import Footer from "$lib/components/Footer.svelte"; import CopyCommand from "$lib/components/CopyCommand.svelte"; import EvidenceThread from "$lib/components/EvidenceThread.svelte";
  import { landingContent } from "$lib/content/landing.ts"; import { translations } from "$lib/i18n/content.ts"; import { landingTranslations } from "$lib/i18n/landing.ts"; import { localeState } from "$lib/i18n/store.svelte.ts";
  let common = $derived(translations[localeState.current]); let copy = $derived(landingTranslations[localeState.current]);
  const problemIcons = [BrainCircuit, Braces, FileWarning, BadgeAlert] as const;
  const trustIcons = [HardDrive, LockKeyhole, UserCheck] as const;
</script>
<svelte:head><title>Phoxia • Kit</title><meta name="description" content={common.subtitle} /></svelte:head>
<Header />
<main id="content">
  <section data-section="hero" class="hero section"><div class="hero-copy"><p class="eyebrow">{copy.eyebrow}</p><h1>{common.title}</h1><p class="lead">{common.subtitle}</p><p>{copy.intro}</p><div class="hero-actions"><a class="button" href="#install">{copy.start}<ArrowRight size={17} /></a><a class="button secondary" href="/docs">{copy.read}</a></div></div><div class="hero-demo"><img src={luxHappy} alt={common.luxLabel} /><div class="terminal"><div class="terminal-bar"><i></i><i></i><i></i><span>terminal</span></div><div class="terminal-body"><div class="terminal-line command"><span>$</span> {landingContent.installCommand}</div><div class="terminal-line brand-line"><b>◆ Phoxia DevKit</b></div><div class="terminal-line">{copy.terminalQuestion}</div><div class="terminal-line">◆ {copy.terminalReading}</div><div class="terminal-line success"><span>✓</span> Claude Code</div><div class="terminal-line success"><span>✓</span> Codex</div><div class="terminal-line ready"><span>✓</span> {copy.terminalReadyLocal}<i aria-hidden="true"></i></div></div></div></div></section>
  <section data-section="problem" class="section problem-section"><div class="section-heading-row"><div class="section-heading"><p class="eyebrow">{copy.problem}</p><h2>{copy.problemTitle}</h2></div><img class="lux-side" src={luxConfused} alt="" /></div><div class="problem-cards">{#each copy.problemCards as card, i}{@const Icon = problemIcons[i]}<article class="problem-card"><span class="icon-tile"><Icon size={19} aria-hidden="true" /></span><h3>{card[0]}</h3><p>{card[1]}</p></article>{/each}</div></section>
  <section data-section="pipeline" id="product" class="wrapper"><EvidenceThread eyebrow={copy.pipeline} title={copy.pipelineTitle} nodes={copy.evidenceNodes} ariaLabel={copy.evidenceAria} /></section>
  <section data-section="workflow" id="how" class="section workflow-section"><div class="row"><div><p class="eyebrow">{copy.workflow}</p><h2>{copy.workflowTitle}</h2></div><img src={luxExplaining} alt="" /></div><div class="workflow-timeline"><i class="timeline-track" aria-hidden="true"></i><i class="timeline-progress" aria-hidden="true"></i><ol>{#each landingContent.workflow as step, i}<li class="timeline-step" style={`--step:${i}`}><span>{i+1}</span><h3>{localeState.current === "pt-BR" ? ["Inicializar","Descrever projeto","Trabalhar com IA","Verificar","Manter sincronizado"][i] : step}</h3></li>{/each}</ol></div></section>
  <section data-section="files-impact" class="section files-impact-section"><p class="eyebrow">{copy.filesImpact}</p><h2>{copy.filesImpactTitle}</h2><div class="file-grid">{#each landingContent.paths.slice(0,3) as path}<article class="file-card"><code>{path}</code><pre>{path === ".phoxia/project.yaml" ? "name: payments-api\ntargets: [claude, codex]" : "# Managed by Phoxia DevKit\nReview before applying."}</pre></article>{/each}</div><div class="verify"><h3>{copy.verify}</h3><p>{copy.verifyText}</p><code>phxdk doctor · phxdk status</code></div><div class="subsection-heading"><p class="eyebrow">{copy.transparency}</p><h3>{copy.transparencyTitle}</h3></div><div class="impact">{#each copy.impact as item}<article class="impact-card"><b>{item[0]}</b><code>{item[1]}</code></article>{/each}</div></section>
  <section data-section="configuration-trust" class="section configuration-trust-section"><p class="eyebrow">{copy.configurationTrust}</p><h2>{copy.configurationTrustTitle}</h2><div class="subsection-heading"><h3>{copy.modesTitle}</h3></div><div class="mode-grid">{#each copy.modeCards as card, i}<article class:recommended={i === 0} class="mode-card"><span>{String(i + 1).padStart(2, "0")}</span><h3>{card[0]}</h3><p>{card[1]}</p></article>{/each}</div><div class="subsection-heading"><h3>{copy.trustTitle}</h3></div><div class="trust-list">{#each copy.trustCards as card, i}{@const Icon = trustIcons[i]}<article class="trust-fact"><span class="icon-tile"><Icon size={19} aria-hidden="true" /></span><h3>{card[0]}</h3><p>{card[1]}</p></article>{/each}</div></section>
  <section data-section="profiles" class="section profiles-section"><p class="eyebrow">{copy.profiles}</p><h2>{copy.profilesTitle}</h2><div class="profile-panels"><article class="profile-panel presets-panel"><h3>{copy.profileCards[0][0]}</h3><p>{copy.profileCards[0][1]}</p><div class="preset-grid">{#each copy.profileCards[0][2].split(" · ") as path}<code class="preset-cell">{path}</code>{/each}</div></article><article class="profile-panel workflows-panel"><h3>{copy.profileCards[1][0]}</h3><p>{copy.profileCards[1][1]}</p><div class="workflow-grid">{#each copy.profileCards[1][2].split(" · ") as path}<code class="workflow-cell">{path}</code>{/each}</div></article></div></section>
  <section data-section="install" id="install" class="section install"><img src={luxHappy} alt=""/><p class="eyebrow">{copy.install}</p><h2>{copy.installTitle}</h2><p>{copy.installText}</p><CopyCommand command={landingContent.installCommand} label={copy.copyCommand} copy={copy.copy} copiedLabel={copy.copied} failedLabel={copy.copyFailed}/><div class="hero-actions"><a class="button" href="/quick-start">{common.getStarted}<ArrowRight size={17}/></a><a class="button secondary" href={landingContent.urls.repository}><Github size={17}/>{copy.github}</a></div></section>
</main>
<Footer />
